name: dianyang
favicon: null
layout_spectrum: 0.6426943300757557
typography_spectrum: 0.8923339615575969
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5192575873807073
  lightness: 0.6245065941475332
  saturation: 0.5685905148275197
  rhythmicContrast: 0.9873357776086777
purpose: []
